### ISSUE TITLE
Batch generate trace pictures with chrome? 

### ISSUE THREAD

**Issue by mathomp4** [nico/ninjatracing#21]
Random question for the great @nico: Do you know if there is a way to "automate" with ninjatracing and chrome? That is I run ninja install, then ninjatracing, and then somehow chrome from the commandline on the json and then, in the end, have a nice png of the trace? 

My guess: heck no, but I thought I'd ask 😄

**Comment by chrfle** [comment]
That would be so nice to stick in jenkins.

But perhaps one should just write a jenkins plugin for parsing the ninja_log instead ^_^

**Comment by mathomp4** [comment]
> That would be so nice to stick in jenkins.
> 
> But perhaps one should just write a jenkins plugin for parsing the ninja_log instead ^_^

@chrfle Ah...if one can run Jenkins. Jenkins plus computing center security is...exciting. :)

**Comment by nico** [comment]
I'm guessing you can get that to work using e.g. the webdriver API, or even using trace renderers that aren't chrome (such as https://speedscope.app/, https://perfetto.dev/). Let us know if you get something working, but it's kind of out-of-scope for this project :)

(In case the answer is still useful, uhm, well over one year later...)
